version: '3.3'
services:
  mautic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      MAUTIC_DB_HOST: db
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticpassword
    depends_on:
      - db
    networks:
      - coolify

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticpassword
    networks:
      - coolify

networks:
  coolify:
    driver: bridge
